FILE_PATH: str = 'file_path'
OUTPUT_FILE_NAME: str = 'output_file_name'
CIPHER_KEY: str = 'cipher_key'
OK: str = 'Ok'
CANCEL: str = 'Cancel'
CONTENT: str = 'content'
UTF_8: str = 'utf-8'
FILE_TYPE: str = 'file_type'
